-- TomoBoss — Catalogue vocal (généré). Ne pas éditer à la main.
-- Pack audio : VoixFrancaise02 (Melune). Voix française.
---@diagnostic disable: undefined-global
local NS = select(2, ...)
NS.Voice = NS.Voice or {}
-- id (clé moteur) -> { fr = nom affiché, cn = clé d'origine, file = fichier, cat = catégorie }
NS.Voice.Catalog = {
    ["54321"] = { fr = "5-4-3-2-1", cn = "54321", file = "54321.ogg", cat = "Compte à rebours" },
    ["aim-note"] = { fr = "Vise la note", cn = "瞄准音符", file = "aim-note.ogg", cat = "Général" },
    ["aoe"] = { fr = "AoE", cn = "AOE", file = "aoe.ogg", cat = "Général" },
    ["aoe-after-5s"] = { fr = "AoE dans 5s", cn = "5秒后AOE", file = "aoe-after-5s.ogg", cat = "Général" },
    ["aoe-continuous"] = { fr = "AoE continue", cn = "持续AOE", file = "aoe-continuous.ogg", cat = "Général" },
    ["approach-boss"] = { fr = "Colle le boss", cn = "靠近BOSS", file = "approach-boss.ogg", cat = "Général" },
    ["approach-link"] = { fr = "Rejoins le lien", cn = "靠近连线", file = "approach-link.ogg", cat = "Général" },
    ["away-add"] = { fr = "Éloigne l'add", cn = "远离大怪", file = "away-add.ogg", cat = "Général" },
    ["away-boss"] = { fr = "Éloigne-toi du boss", cn = "远离BOSS", file = "away-boss.ogg", cat = "Général" },
    ["away-group"] = { fr = "Éloigne-toi du groupe", cn = "远离人群", file = "away-group.ogg", cat = "Général" },
    ["beam-on-you"] = { fr = "Rayon sur toi", cn = "射线点你", file = "beam-on-you.ogg", cat = "Général" },
    ["big-adds"] = { fr = "Gros adds", cn = "召唤大怪", file = "big-adds.ogg", cat = "Général" },
    ["block-ball"] = { fr = "Bloque la boule", cn = "注意挡球", file = "block-ball.ogg", cat = "Général" },
    ["boss-enrage"] = { fr = "Boss enragé", cn = "Boss狂暴", file = "boss-enrage.ogg", cat = "Général" },
    ["boss-vuln"] = { fr = "Boss vulnérable", cn = "Boss易伤", file = "boss-vuln.ogg", cat = "Général" },
    ["break-link"] = { fr = "Casse le lien", cn = "拉断连线", file = "break-link.ogg", cat = "Général" },
    ["break-shield"] = { fr = "Casse le bouclier", cn = "快破盾", file = "break-shield.ogg", cat = "Général" },
    ["cc-add"] = { fr = "CC l'add", cn = "控制小怪", file = "cc-add.ogg", cat = "Général" },
    ["cc-cast"] = { fr = "CC l'incantation", cn = "控断钢条", file = "cc-cast.ogg", cat = "Général" },
    ["clear-ball"] = { fr = "Absorbe la boule", cn = "注意消球", file = "clear-ball.ogg", cat = "Général" },
    ["clear-link"] = { fr = "Retire le lien", cn = "消除连线", file = "clear-link.ogg", cat = "Général" },
    ["clear-water"] = { fr = "Nettoie l'eau", cn = "快去消水", file = "clear-water.ogg", cat = "Général" },
    ["countdown-1"] = { fr = "1", cn = "1", file = "countdown-1.ogg", cat = "Compte à rebours" },
    ["countdown-2"] = { fr = "2", cn = "2", file = "countdown-2.ogg", cat = "Compte à rebours" },
    ["countdown-3"] = { fr = "3", cn = "3", file = "countdown-3.ogg", cat = "Compte à rebours" },
    ["countdown-4"] = { fr = "4", cn = "4", file = "countdown-4.ogg", cat = "Compte à rebours" },
    ["countdown-5"] = { fr = "5", cn = "5", file = "countdown-5.ogg", cat = "Compte à rebours" },
    ["dodge-beam"] = { fr = "Esquive le rayon", cn = "躲射线", file = "dodge-beam.ogg", cat = "Esquive" },
    ["dodge-charge"] = { fr = "Esquive la charge", cn = "躲开冲锋", file = "dodge-charge.ogg", cat = "Esquive" },
    ["dodge-circle"] = { fr = "Esquive le cercle", cn = "躲圈", file = "dodge-circle.ogg", cat = "Esquive" },
    ["dodge-frontal"] = { fr = "Esquive le frontal", cn = "躲开头前", file = "dodge-frontal.ogg", cat = "Esquive" },
    ["dodge-now"] = { fr = "Esquive !", cn = "快躲开", file = "dodge-now.ogg", cat = "Esquive" },
    ["dodge-orb"] = { fr = "Esquive l'orbe", cn = "躲球", file = "dodge-orb.ogg", cat = "Esquive" },
    ["dodge-repeat"] = { fr = "Esquives répétées", cn = "连续躲圈", file = "dodge-repeat.ogg", cat = "Esquive" },
    ["drop-water"] = { fr = "Dépose l'eau", cn = "出去放水", file = "drop-water.ogg", cat = "Général" },
    ["drop-water-edge"] = { fr = "Eau sur le bord", cn = "贴边放水", file = "drop-water-edge.ogg", cat = "Général" },
    ["empower-hpal"] = { fr = "Renforce le pala heal", cn = "强化奶骑", file = "empower-hpal.ogg", cat = "Général" },
    ["empower-prot"] = { fr = "Renforce le pala prot", cn = "强化防骑", file = "empower-prot.ogg", cat = "Général" },
    ["empower-ret"] = { fr = "Renforce le pala vindicte", cn = "强化惩戒骑", file = "empower-ret.ogg", cat = "Général" },
    ["enter-bubble"] = { fr = "Entre dans la bulle", cn = "快进罩子", file = "enter-bubble.ogg", cat = "Général" },
    ["find-beacon"] = { fr = "Trouve le faisceau", cn = "快找光柱", file = "find-beacon.ogg", cat = "Général" },
    ["fix-camera"] = { fr = "Bloque la caméra", cn = "快卡视角", file = "fix-camera.ogg", cat = "Général" },
    ["get-buff"] = { fr = "Prends le buff", cn = "获得增益", file = "get-buff.ogg", cat = "Général" },
    ["heal-absorb"] = { fr = "Absorption de soin", cn = "吸收治疗", file = "heal-absorb.ogg", cat = "Général" },
    ["hit-back"] = { fr = "Frappe dans le dos", cn = "打背面", file = "hit-back.ogg", cat = "Général" },
    ["hit-clone"] = { fr = "Percute le clone", cn = "去撞分身", file = "hit-clone.ogg", cat = "Général" },
    ["hook-boss"] = { fr = "Accroche le boss", cn = "勾BOSS", file = "hook-boss.ogg", cat = "Général" },
    ["intercept-add"] = { fr = "Intercepte l'add", cn = "去接小怪", file = "intercept-add.ogg", cat = "Général" },
    ["interrupt-now"] = { fr = "Interromps !", cn = "快打断", file = "interrupt-now.ogg", cat = "Général" },
    ["kill-orb"] = { fr = "Détruis l'orbe", cn = "快打宝珠", file = "kill-orb.ogg", cat = "Général" },
    ["kite-add"] = { fr = "Kite l'add", cn = "风筝小怪", file = "kite-add.ogg", cat = "Général" },
    ["link-on-you"] = { fr = "Lien sur toi", cn = "连线点你", file = "link-on-you.ogg", cat = "Général" },
    ["massive-aoe"] = { fr = "AoE massive", cn = "超大AOE", file = "massive-aoe.ogg", cat = "Général" },
    ["mirror"] = { fr = "Clone invoqué", cn = "召唤分身", file = "mirror.ogg", cat = "Général" },
    ["move-group"] = { fr = "Déplace le groupe", cn = "集合移动", file = "move-group.ogg", cat = "Général" },
    ["phase-change"] = { fr = "Changement de phase", cn = "转阶段", file = "phase-change.ogg", cat = "Général" },
    ["prepare-absorb-ball"] = { fr = "Prépare l'absorption de boule", cn = "准备吸球", file = "prepare-absorb-ball.ogg", cat = "Préparation" },
    ["prepare-aoe"] = { fr = "Prépare l'AoE", cn = "准备AOE", file = "prepare-aoe.ogg", cat = "Préparation" },
    ["prepare-aoe-break"] = { fr = "Prépare l'AoE (interruption)", cn = "准备AOE(断条)", file = "prepare-aoe-break.ogg", cat = "Préparation" },
    ["prepare-arrow"] = { fr = "Prépare les flèches", cn = "准备踩箭", file = "prepare-arrow.ogg", cat = "Préparation" },
    ["prepare-ball"] = { fr = "Prépare la boule", cn = "准备送球", file = "prepare-ball.ogg", cat = "Préparation" },
    ["prepare-beam"] = { fr = "Prépare le rayon", cn = "准备引线", file = "prepare-beam.ogg", cat = "Préparation" },
    ["prepare-block-line"] = { fr = "Prépare à bloquer la ligne", cn = "准备挡线", file = "prepare-block-line.ogg", cat = "Préparation" },
    ["prepare-clear-stack"] = { fr = "Prépare à purger les stacks", cn = "准备消层", file = "prepare-clear-stack.ogg", cat = "Préparation" },
    ["prepare-dance"] = { fr = "Prépare l'esquive au sol", cn = "准备跑圈", file = "prepare-dance.ogg", cat = "Préparation" },
    ["prepare-dispel"] = { fr = "Prépare la dissipation", cn = "准备驱散", file = "prepare-dispel.ogg", cat = "Préparation" },
    ["prepare-enter-circle"] = { fr = "Prépare à entrer dans le cercle", cn = "准备进圈", file = "prepare-enter-circle.ogg", cat = "Préparation" },
    ["prepare-fixate"] = { fr = "Prépare le focus", cn = "准备追人", file = "prepare-fixate.ogg", cat = "Préparation" },
    ["prepare-grab"] = { fr = "Prépare à saisir", cn = "准备抓人", file = "prepare-grab.ogg", cat = "Préparation" },
    ["prepare-hook"] = { fr = "Prépare l'accroche", cn = "准备钩人", file = "prepare-hook.ogg", cat = "Préparation" },
    ["prepare-interrupt"] = { fr = "Prépare l'interruption", cn = "准备打断", file = "prepare-interrupt.ogg", cat = "Préparation" },
    ["prepare-link"] = { fr = "Prépare le lien", cn = "准备连线", file = "prepare-link.ogg", cat = "Préparation" },
    ["prepare-pull"] = { fr = "Prépare la traction", cn = "准备拉人", file = "prepare-pull.ogg", cat = "Préparation" },
    ["prepare-soak"] = { fr = "Prépare l'absorption", cn = "准备接圈", file = "prepare-soak.ogg", cat = "Préparation" },
    ["prepare-stack"] = { fr = "Prépare le regroupement", cn = "准备集合", file = "prepare-stack.ogg", cat = "Préparation" },
    ["prepare-target"] = { fr = "Prépare le marquage", cn = "准备点名", file = "prepare-target.ogg", cat = "Préparation" },
    ["prepare-vuln"] = { fr = "Prépare la vulnérabilité", cn = "准备易伤", file = "prepare-vuln.ogg", cat = "Préparation" },
    ["rescue-now"] = { fr = "Sauve-le !", cn = "快救人", file = "rescue-now.ogg", cat = "Général" },
    ["rift-on-you"] = { fr = "Faille sur toi", cn = "裂隙点你", file = "rift-on-you.ogg", cat = "Général" },
    ["run-marked"] = { fr = "Cours ! Tu es marqué", cn = "快跑！你被点名", file = "run-marked.ogg", cat = "Marquage" },
    ["run-now"] = { fr = "Cours !", cn = "快跑", file = "run-now.ogg", cat = "Général" },
    ["soak-lightning"] = { fr = "Absorbe l'éclair", cn = "圈住电水", file = "soak-lightning.ogg", cat = "Général" },
    ["sound-ding"] = { fr = "Son : Ding", cn = "音效_叮咚", file = "sound-ding.ogg", cat = "Sons" },
    ["sound-glass"] = { fr = "Son : Verre", cn = "音效_Glass", file = "sound-glass.ogg", cat = "Sons" },
    ["sound-info"] = { fr = "Son : Info", cn = "音效_Info", file = "sound-info.ogg", cat = "Sons" },
    ["special-mechanic"] = { fr = "Mécanique spéciale", cn = "特殊技能", file = "special-mechanic.ogg", cat = "Général" },
    ["spread-close"] = { fr = "Écarte-toi (serré)", cn = "靠近分散", file = "spread-close.ogg", cat = "Général" },
    ["spread-now"] = { fr = "Écartez-vous !", cn = "快分散", file = "spread-now.ogg", cat = "Général" },
    ["stack-drop"] = { fr = "Regroupez et déposez", cn = "集合放圈", file = "stack-drop.ogg", cat = "Général" },
    ["stack-share"] = { fr = "Regroupez pour partager", cn = "集合分摊", file = "stack-share.ogg", cat = "Général" },
    ["std-absorb"] = { fr = "Absorbe", cn = "吸收盾", file = "std-absorb.ogg", cat = "Standard" },
    ["std-add"] = { fr = "Add", cn = "注意大怪", file = "std-add.ogg", cat = "Standard" },
    ["std-adds"] = { fr = "Adds", cn = "小怪快打", file = "std-adds.ogg", cat = "Standard" },
    ["std-arrow"] = { fr = "Flèches", cn = "注意箭矢", file = "std-arrow.ogg", cat = "Standard" },
    ["std-away"] = { fr = "Éloigne-toi", cn = "远离", file = "std-away.ogg", cat = "Standard" },
    ["std-bait"] = { fr = "Appâte", cn = "引导位置", file = "std-bait.ogg", cat = "Standard" },
    ["std-beam"] = { fr = "Rayon", cn = "注意射线", file = "std-beam.ogg", cat = "Standard" },
    ["std-black"] = { fr = "Noir", cn = "黑色", file = "std-black.ogg", cat = "Standard" },
    ["std-blue"] = { fr = "Bleu", cn = "蓝色", file = "std-blue.ogg", cat = "Standard" },
    ["std-bomb"] = { fr = "Bombe", cn = "炸弹", file = "std-bomb.ogg", cat = "Standard" },
    ["std-break"] = { fr = "Casse", cn = "打破", file = "std-break.ogg", cat = "Standard" },
    ["std-breath"] = { fr = "Souffle", cn = "吐息", file = "std-breath.ogg", cat = "Standard" },
    ["std-cc"] = { fr = "CC", cn = "注意控断", file = "std-cc.ogg", cat = "Standard" },
    ["std-chain"] = { fr = "Chaîne", cn = "锁链", file = "std-chain.ogg", cat = "Standard" },
    ["std-charge"] = { fr = "Charge", cn = "冲锋", file = "std-charge.ogg", cat = "Standard" },
    ["std-clear"] = { fr = "Nettoie", cn = "清除", file = "std-clear.ogg", cat = "Standard" },
    ["std-clone"] = { fr = "Clone", cn = "分身", file = "std-clone.ogg", cat = "Standard" },
    ["std-curse"] = { fr = "Malédiction", cn = "诅咒", file = "std-curse.ogg", cat = "Standard" },
    ["std-dance"] = { fr = "Esquive au sol", cn = "躲地板", file = "std-dance.ogg", cat = "Standard" },
    ["std-disease"] = { fr = "Maladie", cn = "疾病", file = "std-disease.ogg", cat = "Standard" },
    ["std-dispel"] = { fr = "Dissipe", cn = "驱散", file = "std-dispel.ogg", cat = "Standard" },
    ["std-dot"] = { fr = "DoT", cn = "持续伤害", file = "std-dot.ogg", cat = "Standard" },
    ["std-drop"] = { fr = "Dépose", cn = "放水", file = "std-drop.ogg", cat = "Standard" },
    ["std-enrage"] = { fr = "Enrage", cn = "激怒", file = "std-enrage.ogg", cat = "Standard" },
    ["std-fixate"] = { fr = "Focus", cn = "追人", file = "std-fixate.ogg", cat = "Standard" },
    ["std-grasp"] = { fr = "Emprise", cn = "抓握", file = "std-grasp.ogg", cat = "Standard" },
    ["std-hook"] = { fr = "Crochet", cn = "注意钩人", file = "std-hook.ogg", cat = "Standard" },
    ["std-in"] = { fr = "Rentre", cn = "进入", file = "std-in.ogg", cat = "Standard" },
    ["std-intermission"] = { fr = "Intermède", cn = "阶段转换", file = "std-intermission.ogg", cat = "Standard" },
    ["std-interrupt"] = { fr = "Interromps", cn = "打断施法", file = "std-interrupt.ogg", cat = "Standard" },
    ["std-kite"] = { fr = "Kite", cn = "风筝", file = "std-kite.ogg", cat = "Standard" },
    ["std-knock"] = { fr = "Repoussé", cn = "击飞", file = "std-knock.ogg", cat = "Standard" },
    ["std-leap"] = { fr = "Bond", cn = "跳跃", file = "std-leap.ogg", cat = "Standard" },
    ["std-line"] = { fr = "Ligne", cn = "连线", file = "std-line.ogg", cat = "Standard" },
    ["std-los"] = { fr = "Coupe la vue", cn = "卡视野", file = "std-los.ogg", cat = "Standard" },
    ["std-mark"] = { fr = "Marque", cn = "点名", file = "std-mark.ogg", cat = "Standard" },
    ["std-move"] = { fr = "Bouge", cn = "移动", file = "std-move.ogg", cat = "Standard" },
    ["std-near"] = { fr = "Rapproche-toi", cn = "靠近", file = "std-near.ogg", cat = "Standard" },
    ["std-orb"] = { fr = "Orbe", cn = "宝珠", file = "std-orb.ogg", cat = "Standard" },
    ["std-out"] = { fr = "Sors !", cn = "出出出", file = "std-out.ogg", cat = "Standard" },
    ["std-pass"] = { fr = "Passe", cn = "传递", file = "std-pass.ogg", cat = "Standard" },
    ["std-refresh"] = { fr = "Rafraîchis", cn = "刷新", file = "std-refresh.ogg", cat = "Standard" },
    ["std-ring"] = { fr = "Grand cercle", cn = "注意大圈", file = "std-ring.ogg", cat = "Standard" },
    ["std-root"] = { fr = "Racines", cn = "定身", file = "std-root.ogg", cat = "Standard" },
    ["std-secure"] = { fr = "Sécurise", cn = "救人", file = "std-secure.ogg", cat = "Standard" },
    ["std-shield"] = { fr = "Bouclier", cn = "护盾", file = "std-shield.ogg", cat = "Standard" },
    ["std-soak"] = { fr = "Absorbe", cn = "吸收", file = "std-soak.ogg", cat = "Standard" },
    ["std-spellsteal"] = { fr = "Vol de sort", cn = "进攻驱散", file = "std-spellsteal.ogg", cat = "Standard" },
    ["std-split"] = { fr = "Sépare", cn = "分裂", file = "std-split.ogg", cat = "Standard" },
    ["std-spread"] = { fr = "Écarte-toi", cn = "分散", file = "std-spread.ogg", cat = "Standard" },
    ["std-stack"] = { fr = "Regroupe", cn = "集合站位", file = "std-stack.ogg", cat = "Standard" },
    ["std-switch"] = { fr = "Change de cible", cn = "目标转换", file = "std-switch.ogg", cat = "Standard" },
    ["std-tank-hit"] = { fr = "Coup sur le tank", cn = "坦克承伤", file = "std-tank-hit.ogg", cat = "Standard" },
    ["std-tank-knock"] = { fr = "Tank repoussé", cn = "坦克击飞", file = "std-tank-knock.ogg", cat = "Standard" },
    ["std-totem"] = { fr = "Totem", cn = "图腾", file = "std-totem.ogg", cat = "Standard" },
    ["std-trap"] = { fr = "Piège", cn = "陷阱", file = "std-trap.ogg", cat = "Standard" },
    ["std-volley"] = { fr = "Salve", cn = "齐射", file = "std-volley.ogg", cat = "Standard" },
    ["std-vulnerability"] = { fr = "Vulnérabilité", cn = "易伤", file = "std-vulnerability.ogg", cat = "Standard" },
    ["std-wave"] = { fr = "Vague", cn = "注意躲波", file = "std-wave.ogg", cat = "Standard" },
    ["std-white"] = { fr = "Blanc", cn = "白色", file = "std-white.ogg", cat = "Standard" },
    ["std-wind"] = { fr = "Vent", cn = "躲风", file = "std-wind.ogg", cat = "Standard" },
    ["std-yellow"] = { fr = "Jaune", cn = "黄色", file = "std-yellow.ogg", cat = "Standard" },
    ["step-trap"] = { fr = "Marche sur le piège", cn = "快踩陷阱", file = "step-trap.ogg", cat = "Général" },
    ["stop-cast"] = { fr = "Arrête d'incanter", cn = "停止施法", file = "stop-cast.ogg", cat = "Général" },
    ["summon-adds"] = { fr = "Invocation d'adds", cn = "召唤小怪", file = "summon-adds.ogg", cat = "Général" },
    ["supply-protocol"] = { fr = "Protocole de ravitaillement", cn = "补给协议", file = "supply-protocol.ogg", cat = "Général" },
    ["switch-add"] = { fr = "Change sur l'add", cn = "转火小怪", file = "switch-add.ogg", cat = "Général" },
    ["switch-boss"] = { fr = "Change sur le boss", cn = "转火大怪", file = "switch-boss.ogg", cat = "Général" },
    ["tank-buster"] = { fr = "Tank buster", cn = "坦克尖刺", file = "tank-buster.ogg", cat = "Tank" },
    ["tank-knockback"] = { fr = "Recul du tank", cn = "坦克击退", file = "tank-knockback.ogg", cat = "Tank" },
    ["target-clear-line"] = { fr = "Marqué : dégage la ligne", cn = "点名消线", file = "target-clear-line.ogg", cat = "Marquage" },
    ["target-drop-water"] = { fr = "Marqué : dépose l'eau", cn = "点名放水", file = "target-drop-water.ogg", cat = "Marquage" },
    ["target-frontal"] = { fr = "Marqué : frontal", cn = "点名头前", file = "target-frontal.ogg", cat = "Marquage" },
    ["target-on-you"] = { fr = "Cible sur toi", cn = "目标是你", file = "target-on-you.ogg", cat = "Marquage" },
    ["use-defensive"] = { fr = "Défensif", cn = "注意减伤", file = "use-defensive.ogg", cat = "Général" },
    ["vuln-burst"] = { fr = "Burst vulnérabilité", cn = "易伤爆发", file = "vuln-burst.ogg", cat = "Général" },
    ["vuln-over"] = { fr = "Vulnérabilité terminée", cn = "易伤结束", file = "vuln-over.ogg", cat = "Général" },
    ["wake-adds"] = { fr = "Réveil des adds", cn = "唤醒小怪", file = "wake-adds.ogg", cat = "Général" },
    ["watch-bomb"] = { fr = "Attention bombe", cn = "小心炸弹", file = "watch-bomb.ogg", cat = "Attention" },
    ["watch-breath"] = { fr = "Attention souffle", cn = "注意吐息", file = "watch-breath.ogg", cat = "Attention" },
    ["watch-circle"] = { fr = "Attention cercle", cn = "注意躲圈", file = "watch-circle.ogg", cat = "Attention" },
    ["watch-dodge"] = { fr = "Attention, esquive", cn = "注意躲避", file = "watch-dodge.ogg", cat = "Attention" },
    ["watch-explosion"] = { fr = "Attention explosion", cn = "小心自爆", file = "watch-explosion.ogg", cat = "Attention" },
    ["watch-frontal"] = { fr = "Attention frontal", cn = "注意头前", file = "watch-frontal.ogg", cat = "Attention" },
    ["watch-healing"] = { fr = "Attention soins", cn = "注意治疗", file = "watch-healing.ogg", cat = "Attention" },
    ["watch-knockback"] = { fr = "Attention recul", cn = "注意击退", file = "watch-knockback.ogg", cat = "Attention" },
    ["watch-launch"] = { fr = "Attention projection", cn = "小心击飞", file = "watch-launch.ogg", cat = "Attention" },
    ["watch-launch-hit"] = { fr = "Attention impact", cn = "注意击飞", file = "watch-launch-hit.ogg", cat = "Attention" },
    ["watch-mark"] = { fr = "Attention marquage", cn = "注意点名", file = "watch-mark.ogg", cat = "Attention" },
    ["watch-shockwave"] = { fr = "Attention onde de choc", cn = "小心冲击波", file = "watch-shockwave.ogg", cat = "Attention" },
    ["watch-step"] = { fr = "Attention au sol", cn = "小心脚下", file = "watch-step.ogg", cat = "Attention" },
    ["watch-wind"] = { fr = "Attention vent", cn = "注意躲风", file = "watch-wind.ogg", cat = "Attention" },
    ["you-black"] = { fr = "Tu es noir", cn = "你是黑色", file = "you-black.ogg", cat = "Marquage" },
    ["you-marked"] = { fr = "Tu es marqué", cn = "你被点名", file = "you-marked.ogg", cat = "Marquage" },
    ["you-white"] = { fr = "Tu es blanc", cn = "你是白色", file = "you-white.ogg", cat = "Marquage" },
}

-- Correspondance clé d'origine (chinois) -> id, pour importer des données de timeline externes
NS.Voice.ByLegacy = {}
for id, e in pairs(NS.Voice.Catalog) do NS.Voice.ByLegacy[e.cn] = id end

