-- TomoBoss — Catalogue vocal (généré). Ne pas éditer à la main.
-- Pack audio : VoixFrancaise02 (Melune). Voix française.
---@diagnostic disable: undefined-global
local NS = select(2, ...)
NS.Voice = NS.Voice or {}
-- id (clé moteur) -> { fr = nom affiché, file = fichier audio, cat = catégorie }
NS.Voice.Catalog = {
    ["54321"] = { fr = "5-4-3-2-1", file = "54321.ogg", cat = "Compte à rebours" },
    ["aim-note"] = { fr = "Vise la note", file = "aim-note.ogg", cat = "Général" },
    ["aoe"] = { fr = "AoE", file = "aoe.ogg", cat = "Général" },
    ["aoe-after-5s"] = { fr = "AoE dans 5s", file = "aoe-after-5s.ogg", cat = "Général" },
    ["aoe-continuous"] = { fr = "AoE continue", file = "aoe-continuous.ogg", cat = "Général" },
    ["approach-boss"] = { fr = "Colle le boss", file = "approach-boss.ogg", cat = "Général" },
    ["approach-link"] = { fr = "Rejoins le lien", file = "approach-link.ogg", cat = "Général" },
    ["away-add"] = { fr = "Éloigne l'add", file = "away-add.ogg", cat = "Général" },
    ["away-boss"] = { fr = "Éloigne-toi du boss", file = "away-boss.ogg", cat = "Général" },
    ["away-group"] = { fr = "Éloigne-toi du groupe", file = "away-group.ogg", cat = "Général" },
    ["beam-on-you"] = { fr = "Rayon sur toi", file = "beam-on-you.ogg", cat = "Général" },
    ["big-adds"] = { fr = "Gros adds", file = "big-adds.ogg", cat = "Général" },
    ["block-ball"] = { fr = "Bloque la boule", file = "block-ball.ogg", cat = "Général" },
    ["boss-enrage"] = { fr = "Boss enragé", file = "boss-enrage.ogg", cat = "Général" },
    ["boss-vuln"] = { fr = "Boss vulnérable", file = "boss-vuln.ogg", cat = "Général" },
    ["break-link"] = { fr = "Casse le lien", file = "break-link.ogg", cat = "Général" },
    ["break-shield"] = { fr = "Casse le bouclier", file = "break-shield.ogg", cat = "Général" },
    ["cc-add"] = { fr = "CC l'add", file = "cc-add.ogg", cat = "Général" },
    ["cc-cast"] = { fr = "CC l'incantation", file = "cc-cast.ogg", cat = "Général" },
    ["clear-ball"] = { fr = "Absorbe la boule", file = "clear-ball.ogg", cat = "Général" },
    ["clear-link"] = { fr = "Retire le lien", file = "clear-link.ogg", cat = "Général" },
    ["clear-water"] = { fr = "Nettoie l'eau", file = "clear-water.ogg", cat = "Général" },
    ["countdown-1"] = { fr = "1", file = "countdown-1.ogg", cat = "Compte à rebours" },
    ["countdown-2"] = { fr = "2", file = "countdown-2.ogg", cat = "Compte à rebours" },
    ["countdown-3"] = { fr = "3", file = "countdown-3.ogg", cat = "Compte à rebours" },
    ["countdown-4"] = { fr = "4", file = "countdown-4.ogg", cat = "Compte à rebours" },
    ["countdown-5"] = { fr = "5", file = "countdown-5.ogg", cat = "Compte à rebours" },
    ["dodge-beam"] = { fr = "Esquive le rayon", file = "dodge-beam.ogg", cat = "Esquive" },
    ["dodge-charge"] = { fr = "Esquive la charge", file = "dodge-charge.ogg", cat = "Esquive" },
    ["dodge-circle"] = { fr = "Esquive le cercle", file = "dodge-circle.ogg", cat = "Esquive" },
    ["dodge-frontal"] = { fr = "Esquive le frontal", file = "dodge-frontal.ogg", cat = "Esquive" },
    ["dodge-now"] = { fr = "Esquive !", file = "dodge-now.ogg", cat = "Esquive" },
    ["dodge-orb"] = { fr = "Esquive l'orbe", file = "dodge-orb.ogg", cat = "Esquive" },
    ["dodge-repeat"] = { fr = "Esquives répétées", file = "dodge-repeat.ogg", cat = "Esquive" },
    ["drop-water"] = { fr = "Dépose l'eau", file = "drop-water.ogg", cat = "Général" },
    ["drop-water-edge"] = { fr = "Eau sur le bord", file = "drop-water-edge.ogg", cat = "Général" },
    ["empower-hpal"] = { fr = "Renforce le pala heal", file = "empower-hpal.ogg", cat = "Général" },
    ["empower-prot"] = { fr = "Renforce le pala prot", file = "empower-prot.ogg", cat = "Général" },
    ["empower-ret"] = { fr = "Renforce le pala vindicte", file = "empower-ret.ogg", cat = "Général" },
    ["enter-bubble"] = { fr = "Entre dans la bulle", file = "enter-bubble.ogg", cat = "Général" },
    ["find-beacon"] = { fr = "Trouve le faisceau", file = "find-beacon.ogg", cat = "Général" },
    ["fix-camera"] = { fr = "Bloque la caméra", file = "fix-camera.ogg", cat = "Général" },
    ["get-buff"] = { fr = "Prends le buff", file = "get-buff.ogg", cat = "Général" },
    ["heal-absorb"] = { fr = "Absorption de soin", file = "heal-absorb.ogg", cat = "Général" },
    ["hit-back"] = { fr = "Frappe dans le dos", file = "hit-back.ogg", cat = "Général" },
    ["hit-clone"] = { fr = "Percute le clone", file = "hit-clone.ogg", cat = "Général" },
    ["hook-boss"] = { fr = "Accroche le boss", file = "hook-boss.ogg", cat = "Général" },
    ["intercept-add"] = { fr = "Intercepte l'add", file = "intercept-add.ogg", cat = "Général" },
    ["interrupt-now"] = { fr = "Interromps !", file = "interrupt-now.ogg", cat = "Général" },
    ["kill-orb"] = { fr = "Détruis l'orbe", file = "kill-orb.ogg", cat = "Général" },
    ["kite-add"] = { fr = "Kite l'add", file = "kite-add.ogg", cat = "Général" },
    ["link-on-you"] = { fr = "Lien sur toi", file = "link-on-you.ogg", cat = "Général" },
    ["massive-aoe"] = { fr = "AoE massive", file = "massive-aoe.ogg", cat = "Général" },
    ["mirror"] = { fr = "Clone invoqué", file = "mirror.ogg", cat = "Général" },
    ["move-group"] = { fr = "Déplace le groupe", file = "move-group.ogg", cat = "Général" },
    ["phase-change"] = { fr = "Changement de phase", file = "phase-change.ogg", cat = "Général" },
    ["prepare-absorb-ball"] = { fr = "Prépare l'absorption de boule", file = "prepare-absorb-ball.ogg", cat = "Préparation" },
    ["prepare-aoe"] = { fr = "Prépare l'AoE", file = "prepare-aoe.ogg", cat = "Préparation" },
    ["prepare-aoe-break"] = { fr = "Prépare l'AoE (interruption)", file = "prepare-aoe-break.ogg", cat = "Préparation" },
    ["prepare-arrow"] = { fr = "Prépare les flèches", file = "prepare-arrow.ogg", cat = "Préparation" },
    ["prepare-ball"] = { fr = "Prépare la boule", file = "prepare-ball.ogg", cat = "Préparation" },
    ["prepare-beam"] = { fr = "Prépare le rayon", file = "prepare-beam.ogg", cat = "Préparation" },
    ["prepare-block-line"] = { fr = "Prépare à bloquer la ligne", file = "prepare-block-line.ogg", cat = "Préparation" },
    ["prepare-clear-stack"] = { fr = "Prépare à purger les stacks", file = "prepare-clear-stack.ogg", cat = "Préparation" },
    ["prepare-dance"] = { fr = "Prépare l'esquive au sol", file = "prepare-dance.ogg", cat = "Préparation" },
    ["prepare-dispel"] = { fr = "Prépare la dissipation", file = "prepare-dispel.ogg", cat = "Préparation" },
    ["prepare-enter-circle"] = { fr = "Prépare à entrer dans le cercle", file = "prepare-enter-circle.ogg", cat = "Préparation" },
    ["prepare-fixate"] = { fr = "Prépare le focus", file = "prepare-fixate.ogg", cat = "Préparation" },
    ["prepare-grab"] = { fr = "Prépare à saisir", file = "prepare-grab.ogg", cat = "Préparation" },
    ["prepare-hook"] = { fr = "Prépare l'accroche", file = "prepare-hook.ogg", cat = "Préparation" },
    ["prepare-interrupt"] = { fr = "Prépare l'interruption", file = "prepare-interrupt.ogg", cat = "Préparation" },
    ["prepare-link"] = { fr = "Prépare le lien", file = "prepare-link.ogg", cat = "Préparation" },
    ["prepare-pull"] = { fr = "Prépare la traction", file = "prepare-pull.ogg", cat = "Préparation" },
    ["prepare-soak"] = { fr = "Prépare l'absorption", file = "prepare-soak.ogg", cat = "Préparation" },
    ["prepare-stack"] = { fr = "Prépare le regroupement", file = "prepare-stack.ogg", cat = "Préparation" },
    ["prepare-target"] = { fr = "Prépare le marquage", file = "prepare-target.ogg", cat = "Préparation" },
    ["prepare-vuln"] = { fr = "Prépare la vulnérabilité", file = "prepare-vuln.ogg", cat = "Préparation" },
    ["rescue-now"] = { fr = "Sauve-le !", file = "rescue-now.ogg", cat = "Général" },
    ["rift-on-you"] = { fr = "Faille sur toi", file = "rift-on-you.ogg", cat = "Général" },
    ["run-marked"] = { fr = "Cours ! Tu es marqué", file = "run-marked.ogg", cat = "Marquage" },
    ["run-now"] = { fr = "Cours !", file = "run-now.ogg", cat = "Général" },
    ["soak-lightning"] = { fr = "Absorbe l'éclair", file = "soak-lightning.ogg", cat = "Général" },
    ["sound-ding"] = { fr = "Son : Ding", file = "sound-ding.ogg", cat = "Sons" },
    ["sound-glass"] = { fr = "Son : Verre", file = "sound-glass.ogg", cat = "Sons" },
    ["sound-info"] = { fr = "Son : Info", file = "sound-info.ogg", cat = "Sons" },
    ["special-mechanic"] = { fr = "Mécanique spéciale", file = "special-mechanic.ogg", cat = "Général" },
    ["spread-close"] = { fr = "Écarte-toi (serré)", file = "spread-close.ogg", cat = "Général" },
    ["spread-now"] = { fr = "Écartez-vous !", file = "spread-now.ogg", cat = "Général" },
    ["stack-drop"] = { fr = "Regroupez et déposez", file = "stack-drop.ogg", cat = "Général" },
    ["stack-share"] = { fr = "Regroupez pour partager", file = "stack-share.ogg", cat = "Général" },
    ["std-absorb"] = { fr = "Absorbe", file = "std-absorb.ogg", cat = "Standard" },
    ["std-add"] = { fr = "Add", file = "std-add.ogg", cat = "Standard" },
    ["std-adds"] = { fr = "Adds", file = "std-adds.ogg", cat = "Standard" },
    ["std-arrow"] = { fr = "Flèches", file = "std-arrow.ogg", cat = "Standard" },
    ["std-away"] = { fr = "Éloigne-toi", file = "std-away.ogg", cat = "Standard" },
    ["std-bait"] = { fr = "Appâte", file = "std-bait.ogg", cat = "Standard" },
    ["std-beam"] = { fr = "Rayon", file = "std-beam.ogg", cat = "Standard" },
    ["std-black"] = { fr = "Noir", file = "std-black.ogg", cat = "Standard" },
    ["std-blue"] = { fr = "Bleu", file = "std-blue.ogg", cat = "Standard" },
    ["std-bomb"] = { fr = "Bombe", file = "std-bomb.ogg", cat = "Standard" },
    ["std-break"] = { fr = "Casse", file = "std-break.ogg", cat = "Standard" },
    ["std-breath"] = { fr = "Souffle", file = "std-breath.ogg", cat = "Standard" },
    ["std-cc"] = { fr = "CC", file = "std-cc.ogg", cat = "Standard" },
    ["std-chain"] = { fr = "Chaîne", file = "std-chain.ogg", cat = "Standard" },
    ["std-charge"] = { fr = "Charge", file = "std-charge.ogg", cat = "Standard" },
    ["std-clear"] = { fr = "Nettoie", file = "std-clear.ogg", cat = "Standard" },
    ["std-clone"] = { fr = "Clone", file = "std-clone.ogg", cat = "Standard" },
    ["std-curse"] = { fr = "Malédiction", file = "std-curse.ogg", cat = "Standard" },
    ["std-dance"] = { fr = "Esquive au sol", file = "std-dance.ogg", cat = "Standard" },
    ["std-disease"] = { fr = "Maladie", file = "std-disease.ogg", cat = "Standard" },
    ["std-dispel"] = { fr = "Dissipe", file = "std-dispel.ogg", cat = "Standard" },
    ["std-dot"] = { fr = "DoT", file = "std-dot.ogg", cat = "Standard" },
    ["std-drop"] = { fr = "Dépose", file = "std-drop.ogg", cat = "Standard" },
    ["std-enrage"] = { fr = "Enrage", file = "std-enrage.ogg", cat = "Standard" },
    ["std-fixate"] = { fr = "Focus", file = "std-fixate.ogg", cat = "Standard" },
    ["std-grasp"] = { fr = "Emprise", file = "std-grasp.ogg", cat = "Standard" },
    ["std-hook"] = { fr = "Crochet", file = "std-hook.ogg", cat = "Standard" },
    ["std-in"] = { fr = "Rentre", file = "std-in.ogg", cat = "Standard" },
    ["std-intermission"] = { fr = "Intermède", file = "std-intermission.ogg", cat = "Standard" },
    ["std-interrupt"] = { fr = "Interromps", file = "std-interrupt.ogg", cat = "Standard" },
    ["std-kite"] = { fr = "Kite", file = "std-kite.ogg", cat = "Standard" },
    ["std-knock"] = { fr = "Repoussé", file = "std-knock.ogg", cat = "Standard" },
    ["std-leap"] = { fr = "Bond", file = "std-leap.ogg", cat = "Standard" },
    ["std-line"] = { fr = "Ligne", file = "std-line.ogg", cat = "Standard" },
    ["std-los"] = { fr = "Coupe la vue", file = "std-los.ogg", cat = "Standard" },
    ["std-mark"] = { fr = "Marque", file = "std-mark.ogg", cat = "Standard" },
    ["std-move"] = { fr = "Bouge", file = "std-move.ogg", cat = "Standard" },
    ["std-near"] = { fr = "Rapproche-toi", file = "std-near.ogg", cat = "Standard" },
    ["std-orb"] = { fr = "Orbe", file = "std-orb.ogg", cat = "Standard" },
    ["std-out"] = { fr = "Sors !", file = "std-out.ogg", cat = "Standard" },
    ["std-pass"] = { fr = "Passe", file = "std-pass.ogg", cat = "Standard" },
    ["std-refresh"] = { fr = "Rafraîchis", file = "std-refresh.ogg", cat = "Standard" },
    ["std-ring"] = { fr = "Grand cercle", file = "std-ring.ogg", cat = "Standard" },
    ["std-root"] = { fr = "Racines", file = "std-root.ogg", cat = "Standard" },
    ["std-secure"] = { fr = "Sécurise", file = "std-secure.ogg", cat = "Standard" },
    ["std-shield"] = { fr = "Bouclier", file = "std-shield.ogg", cat = "Standard" },
    ["std-soak"] = { fr = "Absorbe", file = "std-soak.ogg", cat = "Standard" },
    ["std-spellsteal"] = { fr = "Vol de sort", file = "std-spellsteal.ogg", cat = "Standard" },
    ["std-split"] = { fr = "Sépare", file = "std-split.ogg", cat = "Standard" },
    ["std-spread"] = { fr = "Écarte-toi", file = "std-spread.ogg", cat = "Standard" },
    ["std-stack"] = { fr = "Regroupe", file = "std-stack.ogg", cat = "Standard" },
    ["std-switch"] = { fr = "Change de cible", file = "std-switch.ogg", cat = "Standard" },
    ["std-tank-hit"] = { fr = "Coup sur le tank", file = "std-tank-hit.ogg", cat = "Standard" },
    ["std-tank-knock"] = { fr = "Tank repoussé", file = "std-tank-knock.ogg", cat = "Standard" },
    ["std-totem"] = { fr = "Totem", file = "std-totem.ogg", cat = "Standard" },
    ["std-trap"] = { fr = "Piège", file = "std-trap.ogg", cat = "Standard" },
    ["std-volley"] = { fr = "Salve", file = "std-volley.ogg", cat = "Standard" },
    ["std-vulnerability"] = { fr = "Vulnérabilité", file = "std-vulnerability.ogg", cat = "Standard" },
    ["std-wave"] = { fr = "Vague", file = "std-wave.ogg", cat = "Standard" },
    ["std-white"] = { fr = "Blanc", file = "std-white.ogg", cat = "Standard" },
    ["std-wind"] = { fr = "Vent", file = "std-wind.ogg", cat = "Standard" },
    ["std-yellow"] = { fr = "Jaune", file = "std-yellow.ogg", cat = "Standard" },
    ["step-trap"] = { fr = "Marche sur le piège", file = "step-trap.ogg", cat = "Général" },
    ["stop-cast"] = { fr = "Arrête d'incanter", file = "stop-cast.ogg", cat = "Général" },
    ["summon-adds"] = { fr = "Invocation d'adds", file = "summon-adds.ogg", cat = "Général" },
    ["supply-protocol"] = { fr = "Protocole de ravitaillement", file = "supply-protocol.ogg", cat = "Général" },
    ["switch-add"] = { fr = "Change sur l'add", file = "switch-add.ogg", cat = "Général" },
    ["switch-boss"] = { fr = "Change sur le boss", file = "switch-boss.ogg", cat = "Général" },
    ["tank-buster"] = { fr = "Tank buster", file = "tank-buster.ogg", cat = "Tank" },
    ["tank-knockback"] = { fr = "Recul du tank", file = "tank-knockback.ogg", cat = "Tank" },
    ["target-clear-line"] = { fr = "Marqué : dégage la ligne", file = "target-clear-line.ogg", cat = "Marquage" },
    ["target-drop-water"] = { fr = "Marqué : dépose l'eau", file = "target-drop-water.ogg", cat = "Marquage" },
    ["target-frontal"] = { fr = "Marqué : frontal", file = "target-frontal.ogg", cat = "Marquage" },
    ["target-on-you"] = { fr = "Cible sur toi", file = "target-on-you.ogg", cat = "Marquage" },
    ["use-defensive"] = { fr = "Défensif", file = "use-defensive.ogg", cat = "Général" },
    ["vuln-burst"] = { fr = "Burst vulnérabilité", file = "vuln-burst.ogg", cat = "Général" },
    ["vuln-over"] = { fr = "Vulnérabilité terminée", file = "vuln-over.ogg", cat = "Général" },
    ["wake-adds"] = { fr = "Réveil des adds", file = "wake-adds.ogg", cat = "Général" },
    ["watch-bomb"] = { fr = "Attention bombe", file = "watch-bomb.ogg", cat = "Attention" },
    ["watch-breath"] = { fr = "Attention souffle", file = "watch-breath.ogg", cat = "Attention" },
    ["watch-circle"] = { fr = "Attention cercle", file = "watch-circle.ogg", cat = "Attention" },
    ["watch-dodge"] = { fr = "Attention, esquive", file = "watch-dodge.ogg", cat = "Attention" },
    ["watch-explosion"] = { fr = "Attention explosion", file = "watch-explosion.ogg", cat = "Attention" },
    ["watch-frontal"] = { fr = "Attention frontal", file = "watch-frontal.ogg", cat = "Attention" },
    ["watch-healing"] = { fr = "Attention soins", file = "watch-healing.ogg", cat = "Attention" },
    ["watch-knockback"] = { fr = "Attention recul", file = "watch-knockback.ogg", cat = "Attention" },
    ["watch-launch"] = { fr = "Attention projection", file = "watch-launch.ogg", cat = "Attention" },
    ["watch-launch-hit"] = { fr = "Attention impact", file = "watch-launch-hit.ogg", cat = "Attention" },
    ["watch-mark"] = { fr = "Attention marquage", file = "watch-mark.ogg", cat = "Attention" },
    ["watch-shockwave"] = { fr = "Attention onde de choc", file = "watch-shockwave.ogg", cat = "Attention" },
    ["watch-step"] = { fr = "Attention au sol", file = "watch-step.ogg", cat = "Attention" },
    ["watch-wind"] = { fr = "Attention vent", file = "watch-wind.ogg", cat = "Attention" },
    ["you-black"] = { fr = "Tu es noir", file = "you-black.ogg", cat = "Marquage" },
    ["you-marked"] = { fr = "Tu es marqué", file = "you-marked.ogg", cat = "Marquage" },
    ["you-white"] = { fr = "Tu es blanc", file = "you-white.ogg", cat = "Marquage" },
}


