-- TomoBoss — Catalogue vocal (généré). Ne pas éditer à la main.
-- Pack audio : VoixFrancaise02. Voix française.
---@diagnostic disable: undefined-global
local NS = select(2, ...)
NS.Voice = NS.Voice or {}
-- id (clé moteur) -> { fr = nom affiché, file = fichier audio, cat = catégorie }
NS.Voice.Catalog = {
    ["54321"] = { fr = "5-4-3-2-1", file = "54321.ogg", cat = "Compte à rebours" },
    ["aim-note"] = { fr = "Vise la note", file = "aim-note.ogg", cat = "Général" },
    ["aoe"] = { fr = "AoE", file = "aoe.ogg", cat = "Général" },
    ["aoe-after-5s"] = { fr = "AoE dans 5s", file = "aoe-after-5s.ogg", cat = "Général" },
    ["aoe-continuous"] = { fr = "AoE continue", file = "aoe-continuous.ogg", cat = "Général" },
    ["approach-boss"] = { fr = "Colle le boss", file = "approach-boss.ogg", cat = "Général" },
    ["approach-link"] = { fr = "Rejoins le lien", file = "approach-link.ogg", cat = "Général" },
    ["away-add"] = { fr = "Éloigne l'add", file = "away-add.ogg", cat = "Général" },
    ["away-boss"] = { fr = "Éloigne-toi du boss", file = "away-boss.ogg", cat = "Général" },
    ["away-group"] = { fr = "Éloigne-toi du groupe", file = "away-group.ogg", cat = "Général" },
    ["beam-on-you"] = { fr = "Rayon sur toi", file = "beam-on-you.ogg", cat = "Général" },
    ["big-adds"] = { fr = "Gros adds", file = "big-adds.ogg", cat = "Général" },
    ["block-ball"] = { fr = "Bloque la boule", file = "block-ball.ogg", cat = "Général" },
    ["boss-enrage"] = { fr = "Boss enragé", file = "boss-enrage.ogg", cat = "Général" },
    ["boss-vuln"] = { fr = "Boss vulnérable", file = "boss-vuln.ogg", cat = "Général" },
    ["break-link"] = { fr = "Casse le lien", file = "break-link.ogg", cat = "Général" },
    ["break-shield"] = { fr = "Casse le bouclier", file = "break-shield.ogg", cat = "Général" },
    ["cc-add"] = { fr = "CC l'add", file = "cc-add.ogg", cat = "Général" },
    ["cc-cast"] = { fr = "CC l'incantation", file = "cc-cast.ogg", cat = "Général" },
    ["clear-ball"] = { fr = "Absorbe la boule", file = "clear-ball.ogg", cat = "Général" },
    ["clear-link"] = { fr = "Retire le lien", file = "clear-link.ogg", cat = "Général" },
    ["clear-water"] = { fr = "Nettoie l'eau", file = "clear-water.ogg", cat = "Général" },
    ["countdown-1"] = { fr = "1", file = "countdown-1.ogg", cat = "Compte à rebours" },
    ["countdown-2"] = { fr = "2", file = "countdown-2.ogg", cat = "Compte à rebours" },
    ["countdown-3"] = { fr = "3", file = "countdown-3.ogg", cat = "Compte à rebours" },
    ["countdown-4"] = { fr = "4", file = "countdown-4.ogg", cat = "Compte à rebours" },
    ["countdown-5"] = { fr = "5", file = "countdown-5.ogg", cat = "Compte à rebours" },
    ["dodge-beam"] = { fr = "Esquive le rayon", file = "dodge-beam.ogg", cat = "Esquive" },
    ["dodge-charge"] = { fr = "Esquive la charge", file = "dodge-charge.ogg", cat = "Esquive" },
    ["dodge-circle"] = { fr = "Esquive le cercle", file = "dodge-circle.ogg", cat = "Esquive" },
    ["dodge-frontal"] = { fr = "Esquive le frontal", file = "dodge-frontal.ogg", cat = "Esquive" },
    ["dodge-now"] = { fr = "Esquive !", file = "dodge-now.ogg", cat = "Esquive" },
    ["dodge-orb"] = { fr = "Esquive l'orbe", file = "dodge-orb.ogg", cat = "Esquive" },
    ["dodge-repeat"] = { fr = "Esquives répétées", file = "dodge-repeat.ogg", cat = "Esquive" },
    ["drop-water"] = { fr = "Dépose l'eau", file = "drop-water.ogg", cat = "Général" },
    ["drop-water-edge"] = { fr = "Eau sur le bord", file = "drop-water-edge.ogg", cat = "Général" },
    ["empower-hpal"] = { fr = "Renforce le pala heal", file = "empower-hpal.ogg", cat = "Général" },
    ["empower-prot"] = { fr = "Renforce le pala prot", file = "empower-prot.ogg", cat = "Général" },
    ["empower-ret"] = { fr = "Renforce le pala vindicte", file = "empower-ret.ogg", cat = "Général" },
    ["enter-bubble"] = { fr = "Entre dans la bulle", file = "enter-bubble.ogg", cat = "Général" },
    ["find-beacon"] = { fr = "Trouve le faisceau", file = "find-beacon.ogg", cat = "Général" },
    ["fix-camera"] = { fr = "Bloque la caméra", file = "fix-camera.ogg", cat = "Général" },
    ["get-buff"] = { fr = "Prends le buff", file = "get-buff.ogg", cat = "Général" },
    ["heal-absorb"] = { fr = "Absorption de soin", file = "heal-absorb.ogg", cat = "Général" },
    ["hit-back"] = { fr = "Frappe dans le dos", file = "hit-back.ogg", cat = "Général" },
    ["hit-clone"] = { fr = "Percute le clone", file = "hit-clone.ogg", cat = "Général" },
    ["hook-boss"] = { fr = "Accroche le boss", file = "hook-boss.ogg", cat = "Général" },
    ["intercept-add"] = { fr = "Intercepte l'add", file = "intercept-add.ogg", cat = "Général" },
    ["interrupt-now"] = { fr = "Interromps !", file = "interrupt-now.ogg", cat = "Général" },
    ["kill-orb"] = { fr = "Détruis l'orbe", file = "kill-orb.ogg", cat = "Général" },
    ["kite-add"] = { fr = "Kite l'add", file = "kite-add.ogg", cat = "Général" },
    ["link-on-you"] = { fr = "Lien sur toi", file = "link-on-you.ogg", cat = "Général" },
    ["massive-aoe"] = { fr = "AoE massive", file = "massive-aoe.ogg", cat = "Général" },
    ["mirror"] = { fr = "Clone invoqué", file = "mirror.ogg", cat = "Général" },
    ["move-group"] = { fr = "Déplace le groupe", file = "move-group.ogg", cat = "Général" },
    ["phase-change"] = { fr = "Changement de phase", file = "phase-change.ogg", cat = "Général" },
    ["prepare-absorb-ball"] = { fr = "Prépare l'absorption de boule", file = "prepare-absorb-ball.ogg", cat = "Préparation" },
    ["prepare-aoe"] = { fr = "Prépare l'AoE", file = "prepare-aoe.ogg", cat = "Préparation" },
    ["prepare-aoe-break"] = { fr = "Prépare l'AoE (interruption)", file = "prepare-aoe-break.ogg", cat = "Préparation" },
    ["prepare-arrow"] = { fr = "Prépare les flèches", file = "prepare-arrow.ogg", cat = "Préparation" },
    ["prepare-ball"] = { fr = "Prépare la boule", file = "prepare-ball.ogg", cat = "Préparation" },
    ["prepare-beam"] = { fr = "Prépare le rayon", file = "prepare-beam.ogg", cat = "Préparation" },
    ["prepare-block-line"] = { fr = "Prépare à bloquer la ligne", file = "prepare-block-line.ogg", cat = "Préparation" },
    ["prepare-clear-stack"] = { fr = "Prépare à purger les stacks", file = "prepare-clear-stack.ogg", cat = "Préparation" },
    ["prepare-dance"] = { fr = "Prépare l'esquive au sol", file = "prepare-dance.ogg", cat = "Préparation" },
    ["prepare-dispel"] = { fr = "Prépare la dissipation", file = "prepare-dispel.ogg", cat = "Préparation" },
    ["prepare-enter-circle"] = { fr = "Prépare à entrer dans le cercle", file = "prepare-enter-circle.ogg", cat = "Préparation" },
    ["prepare-fixate"] = { fr = "Prépare le focus", file = "prepare-fixate.ogg", cat = "Préparation" },
    ["prepare-grab"] = { fr = "Prépare à saisir", file = "prepare-grab.ogg", cat = "Préparation" },
    ["prepare-hook"] = { fr = "Prépare l'accroche", file = "prepare-hook.ogg", cat = "Préparation" },
    ["prepare-interrupt"] = { fr = "Prépare l'interruption", file = "prepare-interrupt.ogg", cat = "Préparation" },
    ["prepare-link"] = { fr = "Prépare le lien", file = "prepare-link.ogg", cat = "Préparation" },
    ["prepare-pull"] = { fr = "Prépare la traction", file = "prepare-pull.ogg", cat = "Préparation" },
    ["prepare-soak"] = { fr = "Prépare l'absorption", file = "prepare-soak.ogg", cat = "Préparation" },
    ["prepare-stack"] = { fr = "Prépare le regroupement", file = "prepare-stack.ogg", cat = "Préparation" },
    ["prepare-target"] = { fr = "Prépare le marquage", file = "prepare-target.ogg", cat = "Préparation" },
    ["prepare-vuln"] = { fr = "Prépare la vulnérabilité", file = "prepare-vuln.ogg", cat = "Préparation" },
    ["rescue-now"] = { fr = "Sauve-le !", file = "rescue-now.ogg", cat = "Général" },
    ["rift-on-you"] = { fr = "Faille sur toi", file = "rift-on-you.ogg", cat = "Général" },
    ["run-marked"] = { fr = "Cours ! Tu es marqué", file = "run-marked.ogg", cat = "Marquage" },
    ["run-now"] = { fr = "Cours !", file = "run-now.ogg", cat = "Général" },
    ["soak-lightning"] = { fr = "Absorbe l'éclair", file = "soak-lightning.ogg", cat = "Général" },
    ["sound-ding"] = { fr = "Son : Ding", file = "sound-ding.ogg", cat = "Sons" },
    ["sound-glass"] = { fr = "Son : Verre", file = "sound-glass.ogg", cat = "Sons" },
    ["sound-info"] = { fr = "Son : Info", file = "sound-info.ogg", cat = "Sons" },
    ["special-mechanic"] = { fr = "Mécanique spéciale", file = "special-mechanic.ogg", cat = "Général" },
    ["spread-close"] = { fr = "Écarte-toi (serré)", file = "spread-close.ogg", cat = "Général" },
    ["spread-now"] = { fr = "Écartez-vous !", file = "spread-now.ogg", cat = "Général" },
    ["stack-drop"] = { fr = "Regroupez et déposez", file = "stack-drop.ogg", cat = "Général" },
    ["stack-share"] = { fr = "Regroupez pour partager", file = "stack-share.ogg", cat = "Général" },
    ["std-absorb"] = { fr = "Absorbe", file = "std-absorb.ogg", cat = "Standard" },
    ["std-add"] = { fr = "Add", file = "std-add.ogg", cat = "Standard" },
    ["std-adds"] = { fr = "Adds", file = "std-adds.ogg", cat = "Standard" },
    ["std-arrow"] = { fr = "Flèches", file = "std-arrow.ogg", cat = "Standard" },
    ["std-away"] = { fr = "Éloigne-toi", file = "std-away.ogg", cat = "Standard" },
    ["std-bait"] = { fr = "Appâte", file = "std-bait.ogg", cat = "Standard" },
    ["std-beam"] = { fr = "Rayon", file = "std-beam.ogg", cat = "Standard" },
    ["std-black"] = { fr = "Noir", file = "std-black.ogg", cat = "Standard" },
    ["std-blue"] = { fr = "Bleu", file = "std-blue.ogg", cat = "Standard" },
    ["std-bomb"] = { fr = "Bombe", file = "std-bomb.ogg", cat = "Standard" },
    ["std-break"] = { fr = "Casse", file = "std-break.ogg", cat = "Standard" },
    ["std-breath"] = { fr = "Souffle", file = "std-breath.ogg", cat = "Standard" },
    ["std-cc"] = { fr = "CC", file = "std-cc.ogg", cat = "Standard" },
    ["std-chain"] = { fr = "Chaîne", file = "std-chain.ogg", cat = "Standard" },
    ["std-charge"] = { fr = "Charge", file = "std-charge.ogg", cat = "Standard" },
    ["std-clear"] = { fr = "Nettoie", file = "std-clear.ogg", cat = "Standard" },
    ["std-clone"] = { fr = "Clone", file = "std-clone.ogg", cat = "Standard" },
    ["std-curse"] = { fr = "Malédiction", file = "std-curse.ogg", cat = "Standard" },
    ["std-dance"] = { fr = "Esquive au sol", file = "std-dance.ogg", cat = "Standard" },
    ["std-disease"] = { fr = "Maladie", file = "std-disease.ogg", cat = "Standard" },
    ["std-dispel"] = { fr = "Dissipe", file = "std-dispel.ogg", cat = "Standard" },
    ["std-dot"] = { fr = "DoT", file = "std-dot.ogg", cat = "Standard" },
    ["std-drop"] = { fr = "Dépose", file = "std-drop.ogg", cat = "Standard" },
    ["std-enrage"] = { fr = "Enrage", file = "std-enrage.ogg", cat = "Standard" },
    ["std-fixate"] = { fr = "Focus", file = "std-fixate.ogg", cat = "Standard" },
    ["std-grasp"] = { fr = "Emprise", file = "std-grasp.ogg", cat = "Standard" },
    ["std-hook"] = { fr = "Crochet", file = "std-hook.ogg", cat = "Standard" },
    ["std-in"] = { fr = "Rentre", file = "std-in.ogg", cat = "Standard" },
    ["std-intermission"] = { fr = "Intermède", file = "std-intermission.ogg", cat = "Standard" },
    ["std-interrupt"] = { fr = "Interromps", file = "std-interrupt.ogg", cat = "Standard" },
    ["std-kite"] = { fr = "Kite", file = "std-kite.ogg", cat = "Standard" },
    ["std-knock"] = { fr = "Repoussé", file = "std-knock.ogg", cat = "Standard" },
    ["std-leap"] = { fr = "Bond", file = "std-leap.ogg", cat = "Standard" },
    ["std-line"] = { fr = "Ligne", file = "std-line.ogg", cat = "Standard" },
    ["std-los"] = { fr = "Coupe la vue", file = "std-los.ogg", cat = "Standard" },
    ["std-mark"] = { fr = "Marque", file = "std-mark.ogg", cat = "Standard" },
    ["std-move"] = { fr = "Bouge", file = "std-move.ogg", cat = "Standard" },
    ["std-near"] = { fr = "Rapproche-toi", file = "std-near.ogg", cat = "Standard" },
    ["std-orb"] = { fr = "Orbe", file = "std-orb.ogg", cat = "Standard" },
    ["std-out"] = { fr = "Sors !", file = "std-out.ogg", cat = "Standard" },
    ["std-pass"] = { fr = "Passe", file = "std-pass.ogg", cat = "Standard" },
    ["std-refresh"] = { fr = "Rafraîchis", file = "std-refresh.ogg", cat = "Standard" },
    ["std-ring"] = { fr = "Grand cercle", file = "std-ring.ogg", cat = "Standard" },
    ["std-root"] = { fr = "Racines", file = "std-root.ogg", cat = "Standard" },
    ["std-secure"] = { fr = "Sécurise", file = "std-secure.ogg", cat = "Standard" },
    ["std-shield"] = { fr = "Bouclier", file = "std-shield.ogg", cat = "Standard" },
    ["std-soak"] = { fr = "Absorbe", file = "std-soak.ogg", cat = "Standard" },
    ["std-spellsteal"] = { fr = "Vol de sort", file = "std-spellsteal.ogg", cat = "Standard" },
    ["std-split"] = { fr = "Sépare", file = "std-split.ogg", cat = "Standard" },
    ["std-spread"] = { fr = "Écarte-toi", file = "std-spread.ogg", cat = "Standard" },
    ["std-stack"] = { fr = "Regroupe", file = "std-stack.ogg", cat = "Standard" },
    ["std-switch"] = { fr = "Change de cible", file = "std-switch.ogg", cat = "Standard" },
    ["std-tank-hit"] = { fr = "Coup sur le tank", file = "std-tank-hit.ogg", cat = "Standard" },
    ["std-tank-knock"] = { fr = "Tank repoussé", file = "std-tank-knock.ogg", cat = "Standard" },
    ["std-totem"] = { fr = "Totem", file = "std-totem.ogg", cat = "Standard" },
    ["std-trap"] = { fr = "Piège", file = "std-trap.ogg", cat = "Standard" },
    ["std-volley"] = { fr = "Salve", file = "std-volley.ogg", cat = "Standard" },
    ["std-vulnerability"] = { fr = "Vulnérabilité", file = "std-vulnerability.ogg", cat = "Standard" },
    ["std-wave"] = { fr = "Vague", file = "std-wave.ogg", cat = "Standard" },
    ["std-white"] = { fr = "Blanc", file = "std-white.ogg", cat = "Standard" },
    ["std-wind"] = { fr = "Vent", file = "std-wind.ogg", cat = "Standard" },
    ["std-yellow"] = { fr = "Jaune", file = "std-yellow.ogg", cat = "Standard" },
    ["step-trap"] = { fr = "Marche sur le piège", file = "step-trap.ogg", cat = "Général" },
    ["stop-cast"] = { fr = "Arrête d'incanter", file = "stop-cast.ogg", cat = "Général" },
    ["summon-adds"] = { fr = "Invocation d'adds", file = "summon-adds.ogg", cat = "Général" },
    ["supply-protocol"] = { fr = "Protocole de ravitaillement", file = "supply-protocol.ogg", cat = "Général" },
    ["switch-add"] = { fr = "Change sur l'add", file = "switch-add.ogg", cat = "Général" },
    ["switch-boss"] = { fr = "Change sur le boss", file = "switch-boss.ogg", cat = "Général" },
    ["tank-buster"] = { fr = "Tank buster", file = "tank-buster.ogg", cat = "Tank" },
    ["tank-knockback"] = { fr = "Recul du tank", file = "tank-knockback.ogg", cat = "Tank" },
    ["target-clear-line"] = { fr = "Marqué : dégage la ligne", file = "target-clear-line.ogg", cat = "Marquage" },
    ["target-drop-water"] = { fr = "Marqué : dépose l'eau", file = "target-drop-water.ogg", cat = "Marquage" },
    ["target-frontal"] = { fr = "Marqué : frontal", file = "target-frontal.ogg", cat = "Marquage" },
    ["target-on-you"] = { fr = "Cible sur toi", file = "target-on-you.ogg", cat = "Marquage" },
    ["use-defensive"] = { fr = "Défensif", file = "use-defensive.ogg", cat = "Général" },
    ["vuln-burst"] = { fr = "Burst vulnérabilité", file = "vuln-burst.ogg", cat = "Général" },
    ["vuln-over"] = { fr = "Vulnérabilité terminée", file = "vuln-over.ogg", cat = "Général" },
    ["wake-adds"] = { fr = "Réveil des adds", file = "wake-adds.ogg", cat = "Général" },
    ["watch-bomb"] = { fr = "Attention bombe", file = "watch-bomb.ogg", cat = "Attention" },
    ["watch-breath"] = { fr = "Attention souffle", file = "watch-breath.ogg", cat = "Attention" },
    ["watch-circle"] = { fr = "Attention cercle", file = "watch-circle.ogg", cat = "Attention" },
    ["watch-dodge"] = { fr = "Attention, esquive", file = "watch-dodge.ogg", cat = "Attention" },
    ["watch-explosion"] = { fr = "Attention explosion", file = "watch-explosion.ogg", cat = "Attention" },
    ["watch-frontal"] = { fr = "Attention frontal", file = "watch-frontal.ogg", cat = "Attention" },
    ["watch-healing"] = { fr = "Attention soins", file = "watch-healing.ogg", cat = "Attention" },
    ["watch-knockback"] = { fr = "Attention recul", file = "watch-knockback.ogg", cat = "Attention" },
    ["watch-launch"] = { fr = "Attention projection", file = "watch-launch.ogg", cat = "Attention" },
    ["watch-launch-hit"] = { fr = "Attention impact", file = "watch-launch-hit.ogg", cat = "Attention" },
    ["watch-mark"] = { fr = "Attention marquage", file = "watch-mark.ogg", cat = "Attention" },
    ["watch-shockwave"] = { fr = "Attention onde de choc", file = "watch-shockwave.ogg", cat = "Attention" },
    ["watch-step"] = { fr = "Attention au sol", file = "watch-step.ogg", cat = "Attention" },
    ["watch-wind"] = { fr = "Attention vent", file = "watch-wind.ogg", cat = "Attention" },
    ["you-black"] = { fr = "Tu es noir", file = "you-black.ogg", cat = "Marquage" },
    ["you-marked"] = { fr = "Tu es marqué", file = "you-marked.ogg", cat = "Marquage" },
    ["you-white"] = { fr = "Tu es blanc", file = "you-white.ogg", cat = "Marquage" },

    -- ----------------------------------------------------------------
    -- Pack « Anticipation » — annonces de préparation aux sorts à venir.
    --
    -- Ajouté sans rien remplacer : ces annonces portent le préfixe prep-
    -- et cohabitent avec les entrées d'origine, qui gardent leurs voix.
    -- Les libellés viennent du nom de fichier, pas d'une écoute.
    -- ----------------------------------------------------------------
    ["prep-absorb-shield"] = { fr = "Bouclier d'absorption", file = "prep-absorb-shield.ogg", cat = "Anticipation" },
    ["prep-action-click-gate"] = { fr = "Clique la porte", file = "prep-action-click-gate.ogg", cat = "Anticipation" },
    ["prep-action-drop-fire-back"] = { fr = "Pose le feu derrière", file = "prep-action-drop-fire-back.ogg", cat = "Anticipation" },
    ["prep-action-drop-fire-front"] = { fr = "Pose le feu devant", file = "prep-action-drop-fire-front.ogg", cat = "Anticipation" },
    ["prep-action-drop-fire-left"] = { fr = "Pose le feu à gauche", file = "prep-action-drop-fire-left.ogg", cat = "Anticipation" },
    ["prep-action-drop-fire-right"] = { fr = "Pose le feu à droite", file = "prep-action-drop-fire-right.ogg", cat = "Anticipation" },
    ["prep-action-guide-orb"] = { fr = "Guide l'orbe", file = "prep-action-guide-orb.ogg", cat = "Anticipation" },
    ["prep-action-interrupt-1"] = { fr = "Interruption 1", file = "prep-action-interrupt-1.ogg", cat = "Anticipation" },
    ["prep-action-interrupt-2"] = { fr = "Interruption 2", file = "prep-action-interrupt-2.ogg", cat = "Anticipation" },
    ["prep-action-interrupt-3"] = { fr = "Interruption 3", file = "prep-action-interrupt-3.ogg", cat = "Anticipation" },
    ["prep-action-prepare-middle"] = { fr = "Prépare-toi au centre", file = "prep-action-prepare-middle.ogg", cat = "Anticipation" },
    ["prep-action-prepare-orb"] = { fr = "Prépare l'orbe", file = "prep-action-prepare-orb.ogg", cat = "Anticipation" },
    ["prep-action-swap"] = { fr = "Échange", file = "prep-action-swap.ogg", cat = "Anticipation" },
    ["prep-action-wait-gate"] = { fr = "Attends à la porte", file = "prep-action-wait-gate.ogg", cat = "Anticipation" },
    ["prep-adds"] = { fr = "Adds", file = "prep-adds.ogg", cat = "Anticipation" },
    ["prep-aimed"] = { fr = "Tir visé", file = "prep-aimed.ogg", cat = "Anticipation" },
    ["prep-aoe"] = { fr = "AoE", file = "prep-aoe.ogg", cat = "Anticipation" },
    ["prep-aoe-2"] = { fr = "AoE (variante)", file = "prep-aoe-2.ogg", cat = "Anticipation" },
    ["prep-avoid-middle"] = { fr = "Évite le centre", file = "prep-avoid-middle.ogg", cat = "Anticipation" },
    ["prep-away"] = { fr = "Éloigne-toi", file = "prep-away.ogg", cat = "Anticipation" },
    ["prep-back"] = { fr = "Recule", file = "prep-back.ogg", cat = "Anticipation" },
    ["prep-beam"] = { fr = "Rayon", file = "prep-beam.ogg", cat = "Anticipation" },
    ["prep-big-add"] = { fr = "Gros add", file = "prep-big-add.ogg", cat = "Anticipation" },
    ["prep-bleed"] = { fr = "Saignement", file = "prep-bleed.ogg", cat = "Anticipation" },
    ["prep-block-line"] = { fr = "Bloque la ligne", file = "prep-block-line.ogg", cat = "Anticipation" },
    ["prep-block-soul"] = { fr = "Bloque l'âme", file = "prep-block-soul.ogg", cat = "Anticipation" },
    ["prep-break-link"] = { fr = "Casse le lien", file = "prep-break-link.ogg", cat = "Anticipation" },
    ["prep-break-shield"] = { fr = "Casse le bouclier", file = "prep-break-shield.ogg", cat = "Anticipation" },
    ["prep-buff"] = { fr = "Buff", file = "prep-buff.ogg", cat = "Anticipation" },
    ["prep-cc"] = { fr = "CC", file = "prep-cc.ogg", cat = "Anticipation" },
    ["prep-cc-2"] = { fr = "CC (variante)", file = "prep-cc-2.ogg", cat = "Anticipation" },
    ["prep-charge"] = { fr = "Charge", file = "prep-charge.ogg", cat = "Anticipation" },
    ["prep-circle"] = { fr = "Cercle", file = "prep-circle.ogg", cat = "Anticipation" },
    ["prep-clone"] = { fr = "Clone", file = "prep-clone.ogg", cat = "Anticipation" },
    ["prep-close"] = { fr = "Rapproche-toi", file = "prep-close.ogg", cat = "Anticipation" },
    ["prep-count-1"] = { fr = "Décompte 1", file = "prep-count-1.ogg", cat = "Anticipation" },
    ["prep-count-2"] = { fr = "Décompte 2", file = "prep-count-2.ogg", cat = "Anticipation" },
    ["prep-count-3"] = { fr = "Décompte 3", file = "prep-count-3.ogg", cat = "Anticipation" },
    ["prep-count-4"] = { fr = "Décompte 4", file = "prep-count-4.ogg", cat = "Anticipation" },
    ["prep-count-5"] = { fr = "Décompte 5", file = "prep-count-5.ogg", cat = "Anticipation" },
    ["prep-countdown"] = { fr = "Décompte", file = "prep-countdown.ogg", cat = "Anticipation" },
    ["prep-curse"] = { fr = "Malédiction", file = "prep-curse.ogg", cat = "Anticipation" },
    ["prep-curse-stacks"] = { fr = "Cumuls de malédiction", file = "prep-curse-stacks.ogg", cat = "Anticipation" },
    ["prep-dispel"] = { fr = "Dissipe", file = "prep-dispel.ogg", cat = "Anticipation" },
    ["prep-dispel-magic"] = { fr = "Dissipe la magie", file = "prep-dispel-magic.ogg", cat = "Anticipation" },
    ["prep-dispel-tank"] = { fr = "Dissipe le tank", file = "prep-dispel-tank.ogg", cat = "Anticipation" },
    ["prep-do-mechanics"] = { fr = "Fais la mécanique", file = "prep-do-mechanics.ogg", cat = "Anticipation" },
    ["prep-dodge"] = { fr = "Esquive", file = "prep-dodge.ogg", cat = "Anticipation" },
    ["prep-dodge-2"] = { fr = "Esquive (variante)", file = "prep-dodge-2.ogg", cat = "Anticipation" },
    ["prep-dodge-3"] = { fr = "Esquive (variante 3)", file = "prep-dodge-3.ogg", cat = "Anticipation" },
    ["prep-dot"] = { fr = "DoT", file = "prep-dot.ogg", cat = "Anticipation" },
    ["prep-drop"] = { fr = "Pose", file = "prep-drop.ogg", cat = "Anticipation" },
    ["prep-drop-2"] = { fr = "Pose (variante)", file = "prep-drop-2.ogg", cat = "Anticipation" },
    ["prep-drop-soul"] = { fr = "Pose l'âme", file = "prep-drop-soul.ogg", cat = "Anticipation" },
    ["prep-empowered-add"] = { fr = "Add renforcé", file = "prep-empowered-add.ogg", cat = "Anticipation" },
    ["prep-enrage"] = { fr = "Enrage", file = "prep-enrage.ogg", cat = "Anticipation" },
    ["prep-enrage-stacks"] = { fr = "Cumuls d'enrage", file = "prep-enrage-stacks.ogg", cat = "Anticipation" },
    ["prep-five-stars"] = { fr = "Cinq étoiles", file = "prep-five-stars.ogg", cat = "Anticipation" },
    ["prep-fixate"] = { fr = "Fixation", file = "prep-fixate.ogg", cat = "Anticipation" },
    ["prep-food-delivery"] = { fr = "Livraison", file = "prep-food-delivery.ogg", cat = "Anticipation" },
    ["prep-freedom"] = { fr = "Liberté", file = "prep-freedom.ogg", cat = "Anticipation" },
    ["prep-frontal"] = { fr = "Frontal", file = "prep-frontal.ogg", cat = "Anticipation" },
    ["prep-frontal-spike"] = { fr = "Pointe frontale", file = "prep-frontal-spike.ogg", cat = "Anticipation" },
    ["prep-green-barrel"] = { fr = "Baril vert", file = "prep-green-barrel.ogg", cat = "Anticipation" },
    ["prep-group-bleed"] = { fr = "Saignement de groupe", file = "prep-group-bleed.ogg", cat = "Anticipation" },
    ["prep-heal-tank"] = { fr = "Soigne le tank", file = "prep-heal-tank.ogg", cat = "Anticipation" },
    ["prep-housekeeping"] = { fr = "Ménage", file = "prep-housekeeping.ogg", cat = "Anticipation" },
    ["prep-in"] = { fr = "Rentre", file = "prep-in.ogg", cat = "Anticipation" },
    ["prep-in-2"] = { fr = "Rentre (variante)", file = "prep-in-2.ogg", cat = "Anticipation" },
    ["prep-interrupt"] = { fr = "Interromps", file = "prep-interrupt.ogg", cat = "Anticipation" },
    ["prep-kick-customer"] = { fr = "Vire le client", file = "prep-kick-customer.ogg", cat = "Anticipation" },
    ["prep-knock"] = { fr = "Projection", file = "prep-knock.ogg", cat = "Anticipation" },
    ["prep-leap"] = { fr = "Bond", file = "prep-leap.ogg", cat = "Anticipation" },
    ["prep-los"] = { fr = "Ligne de vue", file = "prep-los.ogg", cat = "Anticipation" },
    ["prep-lucio"] = { fr = "Lúcio", file = "prep-lucio.ogg", cat = "Anticipation" },
    ["prep-magic"] = { fr = "Magie", file = "prep-magic.ogg", cat = "Anticipation" },
    ["prep-marked"] = { fr = "Marqué", file = "prep-marked.ogg", cat = "Anticipation" },
    ["prep-marked-2"] = { fr = "Marqué (variante)", file = "prep-marked-2.ogg", cat = "Anticipation" },
    ["prep-move"] = { fr = "Bouge", file = "prep-move.ogg", cat = "Anticipation" },
    ["prep-move-out"] = { fr = "Sors", file = "prep-move-out.ogg", cat = "Anticipation" },
    ["prep-move-to-boss"] = { fr = "Va sur le boss", file = "prep-move-to-boss.ogg", cat = "Anticipation" },
    ["prep-mushrooms-growing"] = { fr = "Champignons qui poussent", file = "prep-mushrooms-growing.ogg", cat = "Anticipation" },
    ["prep-orb"] = { fr = "Orbe", file = "prep-orb.ogg", cat = "Anticipation" },
    ["prep-orb-2"] = { fr = "Orbe (variante)", file = "prep-orb-2.ogg", cat = "Anticipation" },
    ["prep-persistent-aoe"] = { fr = "AoE persistante", file = "prep-persistent-aoe.ogg", cat = "Anticipation" },
    ["prep-phase-change"] = { fr = "Changement de phase", file = "prep-phase-change.ogg", cat = "Anticipation" },
    ["prep-poison"] = { fr = "Poison", file = "prep-poison.ogg", cat = "Anticipation" },
    ["prep-rescue"] = { fr = "Sauvetage", file = "prep-rescue.ogg", cat = "Anticipation" },
    ["prep-safe"] = { fr = "C'est sûr", file = "prep-safe.ogg", cat = "Anticipation" },
    ["prep-shield"] = { fr = "Bouclier", file = "prep-shield.ogg", cat = "Anticipation" },
    ["prep-shield-removed"] = { fr = "Bouclier retiré", file = "prep-shield-removed.ogg", cat = "Anticipation" },
    ["prep-snare"] = { fr = "Entrave", file = "prep-snare.ogg", cat = "Anticipation" },
    ["prep-soak"] = { fr = "Absorbe", file = "prep-soak.ogg", cat = "Anticipation" },
    ["prep-soak-2"] = { fr = "Absorbe (variante)", file = "prep-soak-2.ogg", cat = "Anticipation" },
    ["prep-soak-orb"] = { fr = "Absorbe l'orbe", file = "prep-soak-orb.ogg", cat = "Anticipation" },
    ["prep-soul"] = { fr = "Âme", file = "prep-soul.ogg", cat = "Anticipation" },
    ["prep-spellsteal"] = { fr = "Vol de sort", file = "prep-spellsteal.ogg", cat = "Anticipation" },
    ["prep-spread"] = { fr = "Écartez-vous", file = "prep-spread.ogg", cat = "Anticipation" },
    ["prep-stack"] = { fr = "Regroupement", file = "prep-stack.ogg", cat = "Anticipation" },
    ["prep-stop-casting"] = { fr = "Arrête d'incanter", file = "prep-stop-casting.ogg", cat = "Anticipation" },
    ["prep-switch"] = { fr = "Change de cible", file = "prep-switch.ogg", cat = "Anticipation" },
    ["prep-tank-debuff"] = { fr = "Debuff de tank", file = "prep-tank-debuff.ogg", cat = "Anticipation" },
    ["prep-tank-vulnerability"] = { fr = "Vulnérabilité du tank", file = "prep-tank-vulnerability.ogg", cat = "Anticipation" },
    ["prep-tankbuster"] = { fr = "Tank buster", file = "prep-tankbuster.ogg", cat = "Anticipation" },
    ["prep-totem"] = { fr = "Totem", file = "prep-totem.ogg", cat = "Anticipation" },
    ["prep-vulnerability"] = { fr = "Vulnérabilité", file = "prep-vulnerability.ogg", cat = "Anticipation" },
    ["prep-vulnerability-ended"] = { fr = "Vulnérabilité terminée", file = "prep-vulnerability-ended.ogg", cat = "Anticipation" },
    ["prep-vulnerability-stacks"] = { fr = "Cumuls de vulnérabilité", file = "prep-vulnerability-stacks.ogg", cat = "Anticipation" },
    ["prep-wind"] = { fr = "Vent", file = "prep-wind.ogg", cat = "Anticipation" },
}


